
class DbNames {
  DbNames._();

  static const T_NumericSequence = 'numericSequence';
  static const T_CandidateToDelete = 'candidateToDelete';
  static const T_TypeForSex = 'typeForSex';
  static const T_Users = 'users';
  static const T_RegisteringUser = 'registeringUser';
  static const T_Continent = 'continent';
  static const T_Country = 'country';
  static const T_Language = 'language';
  static const T_BatchKey = 'batchKey';
  static const T_UserToBatch = 'userToBatch';
  static const T_Rights = 'rights';
  static const T_Roles = 'roles';
  static const T_UserToRoles = 'userToRoles';
  static const T_BadWords = 'badWords';
  static const T_ReservedWords = 'reservedWords';
  static const T_UserCountry = 'userCountry';
  static const T_UserCurrency = 'userCurrency';
  static const T_UserBankCard = 'userBankCard';
  static const T_UserPlace = 'userPlace';
  static const T_UserBlockList = 'userBlockList';
  static const T_DevicesCellar = 'devicesCellar';
  static const T_UserNameId = 'userNameId';
  static const T_UserNotifier = 'userNotifier';
  static const T_TypeForUserMetaData = 'typeForUserMetaData';
  static const T_UserMetaData = 'userMetaData';
  static const T_MobileNumber = 'mobileNumber';
  static const T_TypeForUserImage = 'typeForUserImage';
  static const T_UserImages = 'userImages';
  static const T_DeviceConnections = 'deviceConnections';
  static const T_UserConnections = 'userConnections';
  static const T_SystemMessageVsCommon = 'systemMessageVsCommon';
  static const T_SystemMessageVsBatch = 'systemMessageVsBatch';
  static const T_SystemMessageVsUser = 'systemMessageVsUser';
  static const T_SystemMessageResult = 'systemMessageResult';
  static const T_UserPersonalData = 'userPersonalData';
  static const T_UserFitnessData = 'userFitnessData';
  static const T_TypeForUserStation = 'typeForUserStation';
  static const T_TypeForConversation = 'typeForConversation';
  static const T_TypeForConversationState = 'typeForConversationState';
  static const T_TypeForMessage = 'typeForMessage';
  static const T_RightsForConversationActivity = 'rightsForConversationActivity';
  static const T_Ticket = 'ticket';
  static const T_seenTicketMessage = 'seenTicketMessage';
  static const T_TicketMessage = 'ticketMessage';
  static const T_TicketEditedMessage = 'ticketEditedMessage';
  static const T_TicketReplyMessage = 'ticketReplyMessage';
  static const T_Conversation = 'conversation';
  static const T_UserToConversation = 'userToConversation';
  static const T_UserConversationHistory = 'userConversationHistory';
  static const T_seenConversationMessage = 'seenConversationMessage';
  static const T_ConversationMessage = 'conversationMessage';
  static const T_MediaMessageData = 'mediaMessageData';
  static const T_EditedMessage = 'editedMessage';
  static const T_ReplyMessage = 'replyMessage';
  static const T_ForwardMessage = 'forwardMessage';
  static const T_Course = 'course';
  static const T_CourseRequest = 'courseRequest';
  static const T_CourseBuyQuestion = 'courseBuyQuestion';
  //static const T_ConversationToPack = 'conversationToPack';
  static const T_TrainerData = 'trainerData';
  static const T_FoodMaterial = 'foodMaterial';
  static const T_FoodMaterialTranslate = 'foodMaterialTranslate';
  static const T_FoodProgram = 'foodProgram';
  static const T_FoodProgramTree = 'foodProgramTree';
  static const T_ProgramSuggestion = 'ProgramSuggestion';
  static const T_Advertising = 'advertising';
  static const T_AppVersions = 'appVersions';

  //... Sequence ...........................................................................
  static const Seq_User = 'user_seq';
  static const Seq_NewUser = 'new_user_seq';   // numeric
  static const Seq_SystemMessage = 'system_message_seq';
  static const Seq_Conversation = 'conversation_seq';
  static const Seq_ConversationMessageId = 'conversation_message_id_seq'; // numeric
  static const Seq_ticket = 'ticket_seq';
  static const Seq_ticketMessageId = 'ticket_message_id_seq'; // numeric
  static const Seq_MediaId = 'media_id_seq';  // numeric
  static const Seq_MediaGroupId = 'media_group_id_seq';
  static const Seq_Course = 'course_seq';
  static const Seq_Pack = 'pack_seq';
  static const Seq_DiscountVsUser = 'discount_user_seq';
}