name: brandfit_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  alfred: ^0.1.5+1                      # Edited https://pub.dev/packages/alfred
  timezone_utc_offset: ^1.1.0
  dio: 4.0.4                             # https://pub.dev/packages/dio
  http: ^0.13.3
  file: ^6.1.2
  translator: ^0.1.7                    # google
  #reflectable: ^3.0.4


  assistance_kit:
    path: ../AssistanceKit

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
